## Put comments here that give an overall description of what your
## functions do

## The below function takes an invertible matrix and returns a list.

makeCacheMatrix <- function(x = matrix()) {
      inv<-NULL
      set <- function(y) {
            x <<- y
            inv <<- NULL
      }
      setinv <- function(inverse) {
            inv <<- inverse
      }
      get<-function() x
      getinv<-function() inv
      list(set = set, get = get,setinv = setinv,getinv=getinv)
      
}


## The below function takes list generated by makeCacheMatrix() and computes the
## inverse of matrix.

cacheSolve <- function(x, ...) {
      inverse<-x$getinv()
      if (!is.null(inverse)){
            message("Getting cached data")
            return(inverse)
      }
      inverse<-solve(x$get())
      x$setinv(inverse)
      x$getinv()
      ## Return a matrix that is the inverse of 'x'
}
